[package]
name = "rbiteopt"
version = "0.1.0"
authors = ["Mikko Juola <mikjuo@gmail.com>"]
edition = "2018"
links = "rbiteopt"

[dependencies]
libc = "0.2"
rcmaes = { git = "https://github.com/Noeda/rcmaes", rev = "46622d2c5fe68841f5fbf93efed162762650c1a8" }

[build-dependencies]
cc = "1.0"
